# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [600, 330]
                    mode: outbound
        carousel:
            quality: 90
            filters:
                scale:
                    dim: [ 2500, 750 ]
        scale:
            quality: 90
            filters:
                scale:
                    dim: [1000, 700]
        property:
            filters:
            # use and setup the "crop" filter
                crop:
                    # set the size of the cropping area
                    size: [ 1200, 700 ]
                    mode: outbound
        background:
            quality: 75
            filters:
                scale:
                    dim: [ 1900, 700 ]
        medium:
            quality: 75
            filters:
                    scale:
                        dim: [ 600, 600 ]
        icon:
            quality: 75
            filters:
                scale:
                    dim: [ 100, 100 ]

